
development:
  adapter: postgresql
  encoding: unicode
  database: jir_development
  host: localhost
  pool: 5
  username: jir
  password:	jir

test:
  adapter: postgresql
  encoding: unicode
  database: jir_test
  pool: 5
  username: jir
  password: jir