production:
  adapter: postgresql
  encoding: utf8
  # database: jir_development
  # host: localhost
  # password: postgres
  # username: postgres
  database: jitney
  pool: 5
  username: jir
  password: jir
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: utf8
  database: jitney
  pool: 5
  username: hirochi
  password: 123456
  host: localhost
  port: 5432
