production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['PROD_DB_NAME'] %>
  pool: 5
  username: <%= ENV['PROD_DB_USER'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  port: <%= ENV['PROD_DB_PORT'] %>
